### PR TITLE
collapse `RUN` declaration in Dockerfile.

### PR DESCRIPTION
**Pull request by d1snin**
## Checklist

- [x] I have read the [Contributing Guidelines]
- [x] I acknowledge that any submitted code will be licensed under the [ISC License]
- [x] I confirm that submitted code is my own work
- [x] I have tested the code, and confirm that it works

## Enviroment

- Operating System: Linux arch 5.14.5-arch1-1 x86_64 GNU/Linux
- Node version: 14.17.6
- NPM version: 7.24.0

## Description
Please see https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better

[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/CONTRIBUTING.md
[ISC License]: https://github.com/tycrek/ass/blob/master/LICENSE

### CODE REVIEW

**Comment by tycrek** [comment]
Thanks; I'll test this after work today and merge if it's successful on my end

**Comment by d1snin** [comment]
@tycrek

**Comment by d1snin** [comment]
@tycrek

**Review by tycrek — APPROVED** [review]
Tested on my home server (Node 14, NPM 7, Ubuntu 20.04) and it works. Thanks!

**Pull request merged**
