### PR TITLE
add support for postgresql

### PR DESCRIPTION
**Pull request by XWasHere**
## Checklist

- [x] I have read the [Contributing Guidelines]
- [x] I acknowledge that any submitted code will be licensed under the [ISC License]
- [x] I confirm that submitted code is my own work
- [x] I have tested the code, and confirm that it works

## Enviroment

- Operating System: artix linux [Linux 6.5.5-arch1-1-custom x86_64]
- Node version: 20.8.0
- npm version: 10.1.0

## Description
adds support for postgresql to ass and renames `sql` to `database` in userconfig. :3

[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/.github/CONTRIBUTING.md
[ISC License]: https://github.com/tycrek/ass/blob/master/LICENSE

### CODE REVIEW

**Comment by Gauvino** [comment]
Thanks you so much for all your work, you are really helping community right now for the 0.15 version!

**Comment by XWasHere** [comment]
> Thanks you so much for all your work, you are really helping community right now for the 0.15 version!

aaa thank you >w<
this is my first time contributing to a decently sized project so i have no idea what im doing, im really happy i can help somehow

**Comment by Gauvino** [comment]
> > Thanks you so much for all your work, you are really helping community right now for the 0.15 version!
> 
> 
> 
> aaa thank you >w<
> 
> this is my first time contributing to a decently sized project so i have no idea what im doing, im really happy i can help somehow

You're doing a really great job for now so keep it like this and my two im doing my best to help the project as best as I can

**Comment by Gauvino** [comment]
@XWasHere are you planning to add like mariadb or mongo db after ? or does it already support maria ?

**Comment by tycrek** [comment]
**[AUTOMATED MESSAGE]** 🔴 This Pull Request has merge conflicts. Please resolve the conflicts so the PR can be successfully reviewed and merged.

**Comment by tycrek** [comment]
**[AUTOMATED MESSAGE]** 🟢 Conflicts have been resolved.

**Comment by XWasHere** [comment]
> @XWasHere are you planning to add like mariadb or mongo db after ? or does it already support maria ?

i'll likely add support for other db's soon, i just started with postgres since its what i was most familiar with

**Comment by Gauvino** [comment]
> > @XWasHere are you planning to add like mariadb or mongo db after ? or does it already support maria ?
> 
> 
> 
> i'll likely add support for other db's soon, i just started with postgres since its what i was most familiar with

And probably the best

**Review by tycrek — APPROVED** [review]

**Pull request merged**
