### PR TITLE
Add workflow to push image into github docker registry

### PR DESCRIPTION
**Pull request by rainbowdashlabs**
## Checklist

- [x] I have read the [Contributing Guidelines] (Wrong link)
- [x] I acknowledge that any submitted code will be licensed under the [ISC License]
- [x] I confirm that submitted code is my own work
- [x] I have tested the code, and confirm that it works

## Environment

As defined by docker

## Description

This PR adds a workflow which builds a docker image on every push on the master branch, tags and workflow dispatch. This image is then pushed into the github docker registry.

This allows users which use tools like watchtower to automatically keep their images updated and users no longer need do keep a complete repository on their server, which requires constant polling to be up to date. They also removes the need to build a docker image locally, which kinda destroys the reason of docker.

I have also replaced the build in the compose file with a link to the new image registry. The docker image registry for this repository might be set to  private and need to be set to public in order for this to work.

The workflow is confirmed working and has already published an image in my fork:

https://github.com/rainbowdashlabs/ass/pkgs/container/ass

[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/CONTRIBUTING.md
[ISC License]: https://github.com/tycrek/ass/blob/master/LICENSE

### CODE REVIEW

**Comment by Uruknara** [comment]
I was waiting for this thing so much thanks you

**Comment by Uruknara** [comment]
@tycrek now you could probably make a docket image on docket hub and ask linux server io to make you a good image

**Comment by rainbowdashlabs** [comment]
A friendly reminder: it still exists.

**Comment by tycrek** [comment]
Ended up going with #234 for ass 0.15.0 indev branch

**Pull request closed without merging**
